apiVersion: v1
data:
  MONGO_INITDB_DATABASE: admin
kind: ConfigMap
metadata:
  name: purchase-service-db-env-file
---
apiVersion: v1
data:
  MONGO_INITDB_DATABASE: admin
kind: ConfigMap
metadata:
  name: user-service-db-env-file
---
apiVersion: v1
data:
  MONGO_INITDB_DATABASE: admin
kind: ConfigMap
metadata:
  name: policy-service-db-env-file
