apiVersion: apps/v1
kind: Deployment
metadata:
  name: purchase-service
spec:
  selector:
    matchLabels:
      app: purchase-service
  template:
    metadata:
      labels:
        app: purchase-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: purchase-service
          image: purchase-service:v1
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: purchase-service-db-env-file
            - configMapRef:
                name: purchase-service-env-file
            - secretRef:
                name: db-secret-file
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: user-service
          image: user-service:v1
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: user-service-db-env-file
            - configMapRef:
                name: user-service-env-file
            - secretRef:
                name: db-secret-file
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: policy-service
spec:
  selector:
    matchLabels:
      app: policy-service
  template:
    metadata:
      labels:
        app: policy-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: policy-service
          image: policy-service:v1
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: policy-service-db-env-file
            - configMapRef:
                name: policy-service-env-file
            - secretRef:
                name: db-secret-file
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: receipt-service
spec:
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
  selector:
    matchLabels:
      app: receipt-service
  template:
    metadata:
      labels:
        app: receipt-service
    spec:
      containers:
        - name: receipt-service
          image: receipt-service:v1
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: receipt-service-env-file
            - secretRef:
                name: receipt-secret-file
          livenessProbe:
            httpGet:
              port: 5000
              path: /ping
            initialDelaySeconds: 120
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            httpGet:
              port: 5000
              path: /ping
            initialDelaySeconds: 60
            periodSeconds: 30
            failureThreshold: 5
