global:
  scrape_interval: 5s
  scrape_timeout: 5s

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'prometheus:9090'
  - job_name: nodes
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - 'user-service:8080'
          - 'policy-service:8080'
          - 'purchase-service:8080'

